name: designdiary
favicon: null
layout_spectrum: 0.4575010787229985
typography_spectrum: 0.7203895275015384
title: "Vizen's Collection of Design Articles"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.625767613761127
  lightness: 0.703982055420056
  saturation: 0.9223994999192655
  rhythmicContrast: 0.9538681115955114
purpose: []
