name: designdiary
favicon: null
layout_spectrum: 0.3582875004503876
typography_spectrum: 0.47904844488948584
title: Design Diary
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.5662529552355409
  lightness: 0.3128918979782611
  saturation: 0.4086778287310153
  rhythmicContrast: 0.5170252581592649
purpose: []
