name: designdiary
favicon: null
layout_spectrum: 0.60184
typography_spectrum: 0.15609
title: Design Diary
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404040'
    - '#ffffff'
    - '#bdd556'
    - '#f4973f'
    - '#e71f76'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.9538681115955114
purpose: []
