name: designdiary
favicon: null
layout_spectrum: 0.66528
typography_spectrum: 0.15609
title: Design Diary
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404040'
    - '#ffffff'
    - '#bdd556'
    - '#f4973f'
    - '#e71f76'
  brandStrength: 0.25
  lightness: 0.125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
